language: node_js
sudo: false
node_js:
  - '0.10'
  - '0.12'
# We want to support this, but our code coverage library doesn't really work
# well with it, nor does bcrypt.
#  - 'iojs'

branches:
  only:
  - master
  - develop

services:
  - mongodb
  
notifications:
  email: ethan@ethanmick.com